name: Auto-milestone
on:
  workflow_dispatch:
    inputs:
      pr:
        type: string
        required: true

permissions:
  pull-requests: write

# Note: this action runs with write permissions on GITHUB_TOKEN even from forks
# so it must not run untrusted code (such as checking out the pull request)
jobs:
  main:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      # Note: Github will not trigger other actions from this because it uses
      # the GITHUB_TOKEN token
      - name: Run auto-milestone
        uses: grafana/grafana-github-actions-go/auto-milestone@km/add-auto-milestone-logging
        with:
          pr: ${{ inputs.pr }}
          token: ${{ secrets.GITHUB_TOKEN }}
