name: Auto-milestone (manually invoked)
on:
  workflow_dispatch:
    inputs:
      pr:
        type: string
        required: true

permissions:
  pull-requests: write

# Note: this action runs with write permissions on GITHUB_TOKEN even from forks
# so it must not run untrusted code (such as checking out the pull request)
jobs:
  main:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      # Note: Github will not trigger other actions from this because it uses
      # the GITHUB_TOKEN token
      - name: Run auto-milestone
        uses: grafana/grafana-github-actions-go/auto-milestone@7425232fcef2f5c7e93bad3739cad8d68783b496
        with:
          pr: ${{ inputs.pr }}
          token: ${{ secrets.GITHUB_TOKEN }}
